// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYuOssa4g3JWLtBXMTTbTULNdAbdvfN1E',
    appId: '1:493121737541:web:4f43456da00ab3acd8e42c',
    messagingSenderId: '493121737541',
    projectId: 'farmxpert-830b9',
    authDomain: 'farmxpert-830b9.firebaseapp.com',
    storageBucket: 'farmxpert-830b9.firebasestorage.app',
    measurementId: 'G-PFD3GKXJWL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOEihSERarY_PBdSH5Eu7JBxec6VqIo04',
    appId: '1:493121737541:android:a7294e868de581e5d8e42c',
    messagingSenderId: '493121737541',
    projectId: 'farmxpert-830b9',
    storageBucket: 'farmxpert-830b9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCu1CdVMermaU7-BswkYKhP5ACJYOJhMDs',
    appId: '1:493121737541:ios:e36f6c81729ae573d8e42c',
    messagingSenderId: '493121737541',
    projectId: 'farmxpert-830b9',
    storageBucket: 'farmxpert-830b9.firebasestorage.app',
    iosBundleId: 'com.example.farmxpert',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCu1CdVMermaU7-BswkYKhP5ACJYOJhMDs',
    appId: '1:493121737541:ios:e36f6c81729ae573d8e42c',
    messagingSenderId: '493121737541',
    projectId: 'farmxpert-830b9',
    storageBucket: 'farmxpert-830b9.firebasestorage.app',
    iosBundleId: 'com.example.farmxpert',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYuOssa4g3JWLtBXMTTbTULNdAbdvfN1E',
    appId: '1:493121737541:web:531d2ad192623609d8e42c',
    messagingSenderId: '493121737541',
    projectId: 'farmxpert-830b9',
    authDomain: 'farmxpert-830b9.firebaseapp.com',
    storageBucket: 'farmxpert-830b9.firebasestorage.app',
    measurementId: 'G-EKL8J1VWPG',
  );
}
